# Generated by Django 5.0.6 on 2024-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='device_id',
            field=models.TextField(default='unknown_device'),
            preserve_default=False,
        ),
    ]
