# Generated by Django 5.0.6 on 2024-06-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_sensordata_co_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='co_level',
            new_name='co_levels',
        ),
    ]
