# Generated by Django 5.0.6 on 2024-06-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_rename_co_level_sensordata_co_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='co_levels',
        ),
    ]
