# Generated by Django 5.0.6 on 2024-06-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_sensordata_co_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='co_level',
            field=models.FloatField(),
        ),
    ]
